### PR TITLE
Custom api Apex Callout Developmemt 

### PR DESCRIPTION
**Pull request by agarwalsanchit1**
Custom api Apex Callout Developmemt  for Feature **How to access a custom end point?**

### CODE REVIEW

**Comment by agarwalsanchit1** [comment]
How to access a custom end point?

**Comment by agarwalsanchit1** [comment]
@jottley Please go through the code.

**Comment by jottley** [comment]
@agarwalsanchit1 This looks great! Could you add some tests similar to those in [SObjectsTemplateTest.java](https://github.com/jottley/spring-social-salesforce/blob/master/src/test/java/org/springframework/social/salesforce/api/impl/SObjectsTemplateTest.java)

**Comment by agarwalsanchit1** [comment]
@jottley The changes have been done with the test class.

**Comment by agarwalsanchit1** [comment]
@jottley Please merge if the code looks good to you. :)

**Comment by agarwalsanchit1** [comment]
@jottley  Please merge if the code looks good to you.

**Review by jottley — APPROVED** [review]

**Comment by jottley** [comment]
@agarwalsanchit1 This is a great addition to the code base!  Look for a release of these changes later this week.

**Pull request merged**
